version: 0.0

os: linux

files:
  - source: test/target/regioncheck-0.0.1-SNAPSHOT.jar
    destination: /tmp

  - source: scripts/stop-app.sh
    destination: /tmp

  - source: scripts/start-app.sh
    destination: /tmp

hooks:
  ApplicationStop:
    - location: /tmp/stop-app.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /tmp/start-app.sh
      timeout: 180
      runas: root
