version: 0.0

os: linux

files:
  - source: test/target/regioncheck-0.0.1-SNAPSHOT.jar
    destination: /tmp
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: ./scripts/stop-app.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: ./scripts/start-app.sh
      timeout: 180
      runas: root
