version: 0.2

phases:
  build:
    commands:
       - mvn clean package
artifacts:
  files:
    - 'test/target/regioncheck-0.0.1-SNAPSHOT.jar'
    - scripts/appspec.yml
    - scripts/start-app.sh
    - scripts/stop-app.sh
