version: 0.0

os: linux

files:
  - source: test/target/regioncheck-0.0.1-SNAPSHOT.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: stop-app.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-app.sh
      timeout: 180
      runas: root
